name: Pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:

  test:
    runs-on: ubuntu-latest
    services:
      postgres_db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: stock
        ports:
          - 5432:5432
        options: --health-cmd pg_isready  --health-interval 5s --health-timeout 5s --health-retries 5
    steps:
      - name: Get code
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: java --version

        name: Setup Gradle
      - uses: gradle/actions/setup-gradle@v6

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build dockerfile
        run: docker build .

      - name: Build docker-compose
        run: docker compose up --build